# Use the official Python image as a base
FROM python:3.9-slim

# Set working directory inside the container
WORKDIR /app

# Copy all the application files into the container
COPY . .

# Install Flask
RUN pip install --no-cache-dir flask

# Expose port 80 to be used by AKS service
EXPOSE 80

# Command to run the app
CMD ["python", "app.py"]
